version: '3'
services:
  app:
    build: application
    ports:
     - "3579:3579"
     - "42101:42101"
    environment:
     - REDIS_HOST=redis
    volumes:
     - .:/code
    networks:
      - redis-net
    depends_on:
      - redis
    tty: true

  redis:
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    networks:
      - redis-net
    volumes:
      - redis-data:/data

networks:
  redis-net:

volumes:
  redis-data: